#!/bin/bash

if [ -z ${REQUIRED} ]; then
	echo "  No binaries were specified as REQUIRED."
	exit 1
fi

for BIN in ${REQUIRED[@]}; do
	if [[ -z $(which $BIN) ]]; then
		echo "  Error: Unable to locate $BIN."
		echo "  Please install with your package manager"
		exit 1
	fi
done
