#!/bin/bash

DOCKER=${DOCKER:-docker}
SSH=${SSH:-ssh}
BC=${BC:-bc}
SED=${SED:-sed}
REQUIRED=( ${DOCKER} ${SSH} ${BC} ${SED} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/common
source ${INCLUDEDIR}/os_detect

check_directory  ${DIRECTORY}
check_file       ${DIRECTORY}/gadget.cfg

source ${INCLUDEDIR}/test_ssh

check_directory  ${HOME}/.ssh
check_file       ${HOME}/.ssh/gadget_rsa
check_file       ${HOME}/.ssh/gadget_rsa.pub

source ${DIRECTORY}/gadget.cfg

## Determine general time estimate @ 800kbps [damn the nand]

SIZE="$(${DOCKER} images --format "{{.Size}}" ${name}_${uuid}-img)"

case "${SIZE}" in
	*MB )
		B_SIZE=$(echo "scale=0; (1000*1000*$(echo ${SIZE} | ${SED} 's% MB%%g'))/1" | ${BC} -l)
		;;
	*KB )
		B_SIZE=$(echo "scale=0; (1000*$(echo ${SIZE} | ${SED} 's% KB%%g'))/1" | ${BC} -l)
		;;
	*B  )
		B_SIZE=$(echo "scale=0; ($(echo ${SIZE} | ${SED} 's% B%%g'))/1" | ${BC} -l)
		;;
	*   )
		echo "  ERROR: Size of ${name}_${uuid}-img could not be determined," 1>&3 2>&4
		echo "  ERROR: or it is too large for the gadget" 1>&3 2>&4
		exit 1
		;;
esac

echo "  - Estimated transfer time: $(echo "scale=1; ${B_SIZE}/800000" | bc -l)s" 1>&3 2>&4

## Push the container over ssh

${DOCKER} save ${name}_${uuid}-img | ${SSH} ${SSH_OPTS} -i ${HOME}/.ssh/gadget_rsa root@${IP} -t "docker load"

## Error check and report eg. "gadget_build error 0-15"
RC=${?}; [ ${RC} -ne 0 ] && gadget_error ${BASH_SOURCE##*/} ${RC} ${LINENO}

echo "  - done" 1>&3 2>&4
