#!/bin/bash

CAT=${CAT:-cat}
UUIDGEN=${UUIDGEN:-uuidgen}
BASENAME=${BASENAME:-basename}
READLINK=${READLINK:-readlink}
TR=${TR:-tr}
REQUIRED=( ${CAT} ${UUIDGEN} ${BASENAME} ${READLINK} ${TR} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/common

## Create directory if a custom one was specified, otherwise, using cwd
[ "${DIRECTORY}" != "${PWD}" ] && create_directory ${DIRECTORY}
check_directory  ${DIRECTORY}
create_file      ${DIRECTORY}/gadget.cfg
check_file       ${DIRECTORY}/gadget.cfg
create_file      ${DIRECTORY}/Dockerfile
check_file       ${DIRECTORY}/Dockerfile

## Create scaffolding

echo "project_gadget_version=${GADGET_VERSION}" > ${DIRECTORY}/gadget.cfg
echo "name=$(echo ${DIRECTORY##*/} | tr '[:upper:]' '[:lower:]')" >> ${DIRECTORY}/gadget.cfg
echo "uuid=$(echo $(${UUIDGEN}) | tr '[:upper:]' '[:lower:]')"   >> ${DIRECTORY}/gadget.cfg

${CAT} <<-EOF > ${DIRECTORY}/Dockerfile
FROM armhf/alpine

CMD ["/bin/cat","/etc/os-release"]
EOF

echo "  - done" 1>&3 2>&4
