#!/bin/bash

UNAME=${UNAME:-uname}
REQUIRED=( ${UNAME} )

source ${INCLUDEDIR}/check_required

case "$(${UNAME})" in
	Darwin)
		OS="darwin"
		;;
	Linux)
		OS="linux"
		;;
	MSYS32)
		OS="windows"
		;;
	*)
		echo "  OS version not supported/could not be determined" 1>&3 2>&4
		exit 1
		;;
esac
