#!/bin/bash

SSH=${SSH:-ssh}
SSH_KEYGEN=${SSH_KEYGEN:-ssh-keygen}
SSH_ADD=${SSH_ADD:-ssh-add}
SCP=${SCP:-scp}
MKTEMP=${MKTEMP:-mktemp}
CHMOD=${CHMOD:-chmod}
PING=${PING:-ping}
REQUIRED=( ${SSH} ${SSH_KEYGEN} ${SCP} ${MKTEMP} ${CHMOD} ${PING} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/os_detect
source ${INCLUDEDIR}/common

case "${OS}" in
	"darwin" | "linux" )
		IP="192.168.81.1"
		;;
	"windows" )
		IP="192.168.82.1"
		;;
	*)
		echo "  OS version not supported/could not be determined" 1>&3 2>&4
		echo "  Unable to set applicable IP address" 1>&3 2>&4
		exit 1
		;;
esac


check_directory		${DIRECTORY}
check_file			${DIRECTORY}/gadget.cfg
source				${DIRECTORY}/gadget.cfg
check_directory		${HOME}/.ssh

# copy default key to home ssh dir to ensure privelege control
[ ! -f ${HOME}/.ssh/gadget_default_rsa ] && cp ${INCLUDEDIR}/id_rsa ${HOME}/.ssh/gadget_default_rsa && chmod 600 ${HOME}/.ssh/gadget_default_rsa
[ ! -f ${HOME}/.ssh/gadget_rsa ] && create_new_key

${SSH} ${SSH_OPTS} -oBatchMode=yes -2 -i ${HOME}/.ssh/gadget_rsa root@${IP} -t "echo g_probe_gadget"

## 0 if logs in with available ssh keys, 255 if fails
## On failure, use default key

## NOTE: If a user tries to "bless" more devices than is allowed in OpenSSH's MaxTries setting,
##       they will be blocked from communicating with the device until reboot or service restart

if [ ${?} -ne 0 ]; then
	echo "  - Attempting to connect to device..." 1>&3 2>&4
	${SSH} ${SSH_OPTS} -oBatchMode=yes -2 -i ${HOME}/.ssh/gadget_default_rsa root@${IP} -t "echo g_probe_default"
		
	if [ ${?} -ne 0 ]; then
		echo "  ERROR: Unable to login with local or default credentials." 1>&3 2>&4
		## Should have created gadget_rsa, tried, failed, then tried and failed with default key
		## something is borked
		
		${PING} -W 5 -c 1 ${IP}
		if [ ${?} -eq 0 ]; then
			echo "  ERROR: But the devices is booted and ready," 1>&3 2>&4
			echo "  ERROR: did you leave your ssh keys at home?" 1>&3 2>&4
			## ping can reach it, must be missing keys or something
		else
			echo "  ERROR: Is the device connected?" 1>&3 2>&4
			## PEBKAC
		fi
		
		exit 1
	else
		echo "  - Copying new key to gadget" 1>&3 2>&4
		${SCP} ${SSH_OPTS} -i ${INCLUDEDIR}/id_rsa ${HOME}/.ssh/gadget_rsa.pub root@${IP}:/root/.ssh/authorized_keys
	
		## Error check and report eg. "gadget_build error 0-15"
		RC=${?}; [ ${RC} -ne 0 ] && gadget_error ${BASH_SOURCE##*/} ${RC} ${LINENO}
	fi
fi

check_directory  ${HOME}/.ssh
check_file       ${HOME}/.ssh/gadget_rsa
check_file       ${HOME}/.ssh/gadget_rsa.pub
